- name: variables and username and password from inventory
  hosts: frontend
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "Hello I am learning {{ course }}, Duration: {{ duration }}, Trainer is: {{ trainer }}"
      