- name: understand vars place prefernece
  hosts: local
  onnection: local
  vars:
    greeting: "hello from playbook"
  vars_files:
   - course.yaml
  vars_prompt:
  - name: greeting
    prompt: "please enter the greeting"
    private: true
  tasks:
  - name: print the greeting
    vars:
      Greetings: "Hello from task"
    ansible.builtin.debug:
      msg: "{{ Greeting }}"

# 1. from command line or arguments passed in cmd line will be taken priority
# 2. inventory
#3. 
