- name: play level variables
  hosts: local
  connection: local
  vars:
    COURSE: Ansible # equal to COURSE=Ansible in shell, shell we refer $VAR or ${VAR}
    DURATION: 10HR
    Learner: Manojyoti
  tasks:
  - name: print course information
    ansible.builtin.debug:
    #vars refernce should be surrounded by ""
      msg: "Hello {{ COURSE }}, Course Duration {{ DURATION }}, Learner is {{Learner} }}"

  - name: print course information again
    ansible.builtin.debug:
    #vars refernce should be surrounded by ""
      msg: "Hello {{ COURSE }}, Course Duration {{ DURATION }}, Learner is {{ Learner }} "